### ISSUE TITLE
Dataset at ftp://nssdcftp.gsfc.nasa.gov/pub/data/wind

### ISSUE THREAD

**Issue by nickrsan** [climate-mirror/datasets#185]
ftp://nssdcftp.gsfc.nasa.gov/pub/data/wind

Suggested in a large email containing many urls

**Comment by as-com** [comment]
Not found

**Comment by bofh453** [comment]
Sigh, so every single link of the form ftp://nssdcftp.gsfc.nasa.gov/spacecraft_data/$SPACECRAFT is actually at ftp://nssdcftp.gsfc.nasa.gov/pub/data/$SPACECRAFT

Backup in progress as of a minute ago.

**Comment by gabefair** [comment]
1 Vote to close

**Comment by donbright** [comment]
size estimates with @bohf453 's alternate url

```
lftp -c 'open ftp://nssdcftp.gsfc.nasa.gov/pub/data/wind && du -h -d1'
121G    ./3dp                                                                  
4.2G    ./epact                                                                
497G    ./mfi                                                                  
1.4G    ./orbit                                                                
151G    ./swe                                                                  
77M     ./swics                                                       
102G    ./waves                                                                
870M    ./windnrt                                                         
877G    .

```

**Comment by bkirkbri** [comment]
@gabefair Why do you vote to close? Is this a duplicate or not relevant? Thanks!

**Comment by bkirkbri** [comment]
@bofh453 Were you able to get a mirror of this one?

**Comment by BauerPiepenbrink** [comment]
Downloading...

**Comment by BauerPiepenbrink** [comment]
mirror available at http://176.9.83.61/185
hashdeep file at http://176.9.83.61/185/185_hashdeep.txt (HUGE!)

total dataset-size: 878 GB or 920475212 Byte

**Comment by bkirkbri** [comment]
@BauerPiepenbrink thank you!

**Comment by gabefair** [comment]
I have a complete copy of this data set: 
https://www.dropbox.com/sh/1itpf5nwwwlp609/AAAiE-YoFWabPtGKJZR00p5Ea?dl=0

Computing md5deep now using: `$md5deep -erl`

**Comment by BauerPiepenbrink** [comment]
@gabefair I cross checked with your md5 sums (http://176.9.83.61/185/wind_diff_gabefair.txt) and all the files you have are in my archive as well (except the .listing, but that doesn't matter)

on the other hand, if I check the folder size like you did, I get:

122G    ./3dp
151G    ./swe
4,2G    ./epact
1,4G    ./orbit
498G    ./mfi
79M     ./swics
102G    ./waves
873M    ./windnrt
878G    .

So either there are files missing in your archive or I followed a bunch of symlinks while downloading and have the same files a few times.

However, you could cross check with my hashdeep file to determine why we have different sizes:
http://176.9.83.61/185/185_hashdeep.txt

**Comment by gabefair** [comment]
Thanks for checking this. I investigated and figured out what happened.
We have the same files, nothing is missing. I just learned that `du` will report the "size on disk" and since I use NTFS compression, my numbers were not actual sizes.
I will remove them now and update my other tickets to show the correct size.

Fyi use `du **-b** --max-depth=1 --human-readable`

**Comment by gabefair** [comment]
## 1 vote to close
We have it mirrored twice in this ticket

**Comment by StephWo** [comment]
Be advised:
because of changes in my hardware demands I wont be able to host this or the other datasets any longer after April 2018. Please create a copy if necessary before the end of April.
The Full list of Dataset Issue-Numbers that are mirrored on my server and will not be hosted after April:

162
175
176
184
185
279
291
362

Find all these datasets at http://176.9.83.62 or http://climatemirror1.space
