### ISSUE TITLE
NGDC Water Column Sonar Data

### ISSUE THREAD

**Issue by JeremiahCurtis** [climate-mirror/datasets#368]
Description: "3-D mapping of fish schools and other mid-water marine organisms, assessing biological abundance, species identification, and habitat characterization. These data are also useful for mapping underwater gas seeps and remotely monitoring undersea oil spills."
https://www.ngdc.noaa.gov/mgg/wcd/

Not sure if there is a straightforward download page for these data, but as far as I can tell, they are not on ftp://ftp.ngdc.noaa.gov/ ,which was addressed in issue #292 
I could be mistaken here, but I don't think these data are on the NODC (National Oceanic Data Center) site, either

**Comment by rustyguts** [comment]
I have emailed (wcd.info@noaa.gov) and requested access to the archives.

**Comment by rustyguts** [comment]
@JeremiahCurtis @gabefair. I was hoping you could advise me on this ticket. I have spoken with a man named chuck at the NGDC and he says this dataset is 33TB and on tape. He also says he does not see how it is pertinent to climate change data and that if we want to mirror it we need to send him hard drives. 

If I can negotiate him to upload to a google drive account or something like that this may be worth doing but otherwise, I don't have the hard drives to spare months of shipping back and forth. 

Do we need this?

**Comment by gabefair** [comment]
Hi @RustyGuts it sounds like we don't need this. Thanks for reaching out to your friend. I will close this ticket.
